name: dbe2-app-topico01
services: 
  app_php:
    build: .
    command: > 
            sh -c "cd /var/www/html/ &&
                    composer i &&
                    php -S 0.0.0.0:80 -t src;"
    ports:
      - 8083:80
    volumes:
        - '.:/var/www/html'
    networks:
      - app_net
    depends_on:
      - mariadb
  mariadb:
    image: 'mariadb:latest'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${APP_DB_PASS}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${APP_DB_NAME}'
        MYSQL_USER: '${APP_DB_USER}'
        MYSQL_PASSWORD: '${APP_DB_PASS}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'vol_db:/var/lib/mysql'
    networks:
        - app_net
    healthcheck:
        test:
            - CMD
            - healthcheck.sh
            - '--connect'
            - '--innodb_initialized'
        retries: 3
        timeout: 5s
  phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
          - '${FORWARD_MYADMIN_PORT:-8093}:80'
        environment:
            PMA_HOST: 'mariadb'
        networks:
            - app_net
        depends_on:
            - mariadb
networks:
  app_net:
    driver: bridge
volumes:
  vol_db:
    driver: local