<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <h1>Insert new Produto</h1>
   <form action="/produtos/update/<?php echo $produto['id_prod']?>" method="POST">
        <table>
            <tr>
                <td>Nome:</td>
                <td><input type="text" name="nome" value="<?php echo $produto['nome']?>"/></td>
            </tr>
            <tr>
                <td>Descricao:</td>
                <td>
                    <textarea name="descricao" id="" cols="30" rows="10"><?php echo $produto['descricao']?>
                    </textarea>
                </td>
            </tr>
            <tr>
                <td>Quantidade em Estoque:</td>
                <td><input type="text" name="qtd_estoque" value="<?php echo $produto['qtd_estoque']?>"/></td>
            </tr>
            <tr>
                <td>Preço:</td>
                <td><input type="number" name="preco" value="<?php echo $produto['preco']?>"/></td>
            </tr>
            <tr>
                <td>Importado:</td>
                <td><input type="checkbox" name="importado" <?php echo $produto['importado']?'checked':''?>/></td>
            </tr>
            <tr align="center">
                <td colspan="2"><input type="submit" value="Editar"/></td>
            </tr>
           <tr align="center">
                <td colspan="2"><a href="/produtos" style="display: inline">&#9664;&nbsp;Voltar</a></td>
            </tr>
        </table>
    </form>
</body>

</html>