<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Produtos</title>
</head>
<body>
	<h2>Lista de Produtos</h2>
    <ul>
		<?php foreach ($produtos as $produto): ?>
			<li>
				<a href="/produtos/show/<?php echo $produto['id_prod']?>">
					<?php echo $produto['id_prod'] ?>
				</a>
				| <?php echo $produto['nome'] ?> 
				| R$ <?php echo $produto['preco'] ?>
				<?php if(isset($_SESSION['AUTH'])):?>
				<div style='display:inline'>
					| <a href="/produtos/edit/<?php echo $produto['id_prod']?>">
						Editar
					</a> 
					| <a href="/produtos/delete/<?php echo $produto['id_prod']?>">
						Remover
					</a> 
				<div>
				<?php endif;?>
			</li>
		<?php endforeach ?>
	</ul>
</body>
</html>